#!env zsh
tag=2.2.9
basename=hub-linux-amd64-$tag
url=https://github.com/github/hub/releases/download/v$tag/$basename.tgz
echo Downloading $url
wget -q $url
tar xf $basename.tgz
sudo ./$basename/install
where hub
hub --version
